### ISSUE TITLE
Possible collaboration?

### ISSUE THREAD

**Issue by Wildhoney** [Katochimoto/xblocks#11]
Your idea is similar to [mine](https://github.com/Wildhoney/Standalone) &mdash; might be a nice idea to collaborate on a solution.

**Comment by Katochimoto** [comment]
Hi. Your solution is really similar with [my kernel](https://github.com/Katochimoto/xblocks-core). But now, to move on, I don't have enough feedback from real usage of the library. I will be glad to have your comments, suggestions or additions and will answer any questions about the library.
